name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "17 9 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      MODAL_ENVIRONMENT: vishy-dev
      PUBLIC_BACKEND_URL: https://modal-labs-vishy-dev--seamless-chat-seamlessm4t-asgi-app.modal.run
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup dependencies
        uses: ./.github/actions/setup

      - name: build frontend
        working-directory: frontend
        run: npm run build

      - name: deploy to modal
        run: modal deploy seamless.py
